apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeserver
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nodeserver
  template:
    metadata:
      labels:
        app: nodeserver
    spec:
      containers:
      - image: docker.pkg.github.com/wasinaphat/node-js-argocd/image:latest
        name: nodeserver
        ports:
        - containerPort: 8080
