apiVersion: v1
kind: Service
metadata:
  name: my-cip-service
spec:
  type: LoadBalancer
  selector:
    app: metrics
    department: sales
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000